"""Two commands. Anything else `rg` and `jq` already do better.

    aftersight run python my_agent.py     # record, no code change
    aftersight skill                      # teach your coding agent to read it
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from aftersight import constants

_SITECUSTOMIZE = '''\
# Generated by `aftersight run`. Chains to any real sitecustomize.
import os, sys

_here = os.path.dirname(os.path.abspath(__file__))
sys.path[:] = [p for p in sys.path if os.path.abspath(p) != _here]
sys.modules.pop("sitecustomize", None)
try:
    import sitecustomize  # noqa: F401  the project's own, if it has one
except ImportError:
    pass
try:
    import aftersight.autostart  # noqa: F401
except Exception as exc:  # noqa: BLE001
    print(f"aftersight: autostart failed: {exc}", file=sys.stderr)
'''


def cmd_run(args: argparse.Namespace) -> int:
    """Records a program without editing it.

    A generated `sitecustomize` on PYTHONPATH is how coverage-style tools attach
    to an interpreter they do not control; it also survives `uv run`, `pytest`
    and any wrapper that eventually execs Python.
    """
    if not args.command:
        print("usage: aftersight run <command> [args...]", file=sys.stderr)
        return 2
    staging = tempfile.mkdtemp(prefix="aftersight-")
    try:
        (Path(staging) / "sitecustomize.py").write_text(_SITECUSTOMIZE)
        env = dict(os.environ)
        env[constants.ENV_AUTOSTART] = "1"
        env["PYTHONPATH"] = os.pathsep.join(
            [staging] + ([env["PYTHONPATH"]] if env.get("PYTHONPATH") else []))
        if args.session:
            env[constants.ENV_SESSION] = args.session
        if args.root:
            env[constants.ENV_ROOT] = args.root
        return subprocess.run(args.command, env=env).returncode
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def cmd_skill(args: argparse.Namespace) -> int:
    source = Path(__file__).resolve().parent / "assets" / "skill" / "SKILL.md"
    target = Path(args.into) / "aftersight" / "SKILL.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(source.read_text())
    print(f"installed {target}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="aftersight", description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    run = sub.add_parser("run", help="run a command with recording enabled")
    run.add_argument("--session", help="session id; a resumed session reuses its run folder")
    run.add_argument("--root", help="telemetry root (default .runs)")
    run.add_argument("command", nargs=argparse.REMAINDER)
    run.set_defaults(func=cmd_run)

    skill = sub.add_parser("skill", help="install the Claude Code skill")
    skill.add_argument("--into", default=".claude/skills", help="skills directory")
    skill.set_defaults(func=cmd_skill)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
